- Cargo.lock
- Cargo.toml
At this point, there is no reason to use a git dependency.
> use a released version of Tokio

- Cargo.lock
- Cargo.toml
- src/bin/cli.rs
- src/bin/server.rs
mini-redis uses the CLI derive pattern. Clap does not yet have a release
supporting this pattern. Using structopt allows mini-redis to avoid git
dependencies.
> use structopt instead of Clap

- Cargo.lock
- Cargo.toml
As Tokio [version 0.2.21][1] contains a fix in the broadcast channel that removes a memory leak in mini-redis, I don't think 0.2.20 should be considered the minimum supported version, even if the codebase compiles with that version.
Refs: #38
[1]: https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.21
> Update Tokio to 0.2.21

- src/bin/server.rs
- src/client.rs
- src/frame.rs
- src/parse.rs
* `Vec<Box<Frame>>` -> `Vec<Frame>` (`Frame` is small enough that no additional boxing is needed: `std::mem::size_of::<Frame>() == 40`)
* remove a `.to_string()`
> Remove unnecessary allocations

- Cargo.toml
- README.md
When you run the server like the README says, you get an error:
```shell
$ cargo run --bin server
error: no bin target named `server`
```
Same happens with `cli` also. 
I believe this is happening cos how they are declared in the Cargo:
```toml
[[bin]]
name = "mini-redis-cli"
path = "src/bin/cli.rs"
[[bin]]
name = "mini-redis-server"
path = "src/bin/server.rs"
```
This PR fixes this. Instead of editing README, I edited the Cargo itself cos I thought it will be easier to type `server` often than `mini-redis-server`
> Update Cargo.toml to change `cli` and `server` binary names

- src/server.rs
Based on discussion in the tokio discord around how `shutdown.recv()` on tasks ever completes, I added the explicit drop + comment.
> Add explicit notify_sender drop

- src/cmd/subscribe.rs
I tried to simplify [`Subscribe::apply`][1] by moving things into separate functions.
[1]: https://github.com/tokio-rs/mini-redis/blob/dc8993b56b8b0842243bbc07b06a4dcda4b409c7/src/cmd/subscribe.rs#L94-L207
> try to simplify Subscribe::apply

- src/connection.rs
The `read_frame` function was fairly big. This splits up the function
into a separate `parse_frame` function. This should help with breaking
up the concept of framing into smaller chunks.
> Split `Connection::read_frame` for readability

- src/connection.rs
This is a follow-up to https://github.com/tokio-rs/mini-redis/pull/67#issuecomment-714780717. We decided to punt changes to `AsyncBufRead` in Tokio 0.3, so this comment is no longer correct.
> Remove note about AsyncBufRead

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/cmd/subscribe.rs
- src/frame.rs
- src/server.rs
- tests/server.rs
No major changes to the code. Depends on Tokio 1.0 being released.
> chore: update to Tokio 1.0

- src/connection.rs
The length of `u64::MAX` is 20 characters.
> Update write_decimal max string length

- src/cmd/set.rs
- While constructing the frame, expiration is not checked: added a check and the additional bytes, i.e. PX ms.
- When parsing from "EX" or "PX", it accepts only upper case, added to_uppercase() to the comparison.
> Fix expiration and upppercase check

- src/blocking_client.rs
- src/lib.rs
This PR adds a simple blocking Redis client. 
Open questions:
1. Does the client spawn any tasks, e.g. for periodic pings? If so, a different approach is needed.
2. Should this be a separate crate?
3. Should the module be called `sync_client` instead?
This is introduced for the purpose of being the basis for an article in the tutorial about using async code in synchronous projects.
> Add blocking client

- src/cmd/mod.rs
- src/cmd/ping.rs
Signed-off-by: tison <wander4096@gmail.com>
I'm unsure whether this repo accepts new features, but I meet this requirement when testing redis pipeline feature as
```bash
(echo -e '*1\r\n$4\r\nPING\r\n*1\r\n$4\r\nPING\r\n*1\r\n$4\r\nPING\r\n'; sleep 1) | nc localhost 6379
```
> support PING command for easy testing

- src/cmd/ping.rs
I wanted badly to get rid of this warning every time I try to compile anything.
> Remove unused import

- .github/workflows/ci.yml
- Cargo.toml
- README.md
- src/bin/server.rs
This introduces all the necessary code to be able to send traces to
AWS Xray via `tracing-opentelemetry`. It can be optionally enabled
using the `xray` feature defined on this crate.
Also update the README.md with instructions on how to enable and use
this.
> Add (optional) OpenTelemetry + Xray integration (#95)

- src/bin/server.rs
There is some extra cfg line and comment that we can get rid of, it's making reading the code confusing.
> chore: remove duplicate cfg line and comment

- src/server.rs
The previous drop implementation was a workaround for this, then inexistant API.
> refactor: use `OwnedSemaphore` for connection limiting

- src/server.rs
Thank you for awesome project!
I'm learning a lot from this project about async processing in rust.
I found tiny typo in the run function in server.rs and fixed it.
> Fix tiny typo in server.rs

- .github/workflows/ci.yml
Older versions use node 12 which is no longer supported (end-of-life on April 30, 2022).
> chore: update actions/checkout action to v3

- src/bin/cli.rs
- src/client.rs
- src/cmd/mod.rs
- src/cmd/subscribe.rs
- src/server.rs
- src/shutdown.rs
The "shutdown" in mini-redis is confusing since there are too many "shutdown" in the project and the word itself can be either a noun or a verb. So I changed the name of the variable.
> Remove unnecessary parameter passing and space

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/cli.rs
- src/client.rs
- src/cmd/ping.rs
- tests/client.rs
As said in the commit messages, I made five changes:
- `doc: add command Ping to README`: currently it's missing.
- `change the internal data type of Ping cmd to Bytes`: according to the [Redis protocol](https://redis.io/commands/ping/), the optional data of Ping command could be `Bulk` type. Currently, it's only `Simple` type.
- `rm unnecessary reference`: complained by Cargo clippy.
- `add tracing to Ping cmd`: to keep consistent with other commands. Another alternative is to remove the instrument annotation on `Ping::apply(self, dst: &mut Connection)`.
- `rm unused dependency tracing-futures`
All the tests have been passed.
> Add doc about Ping cmd to README, change the internal data type of Ping cmd to Bytes, and rm unnecessary reference

- src/clients/client.rs
- src/db.rs
Related to the [issue](https://github.com/tokio-rs/mini-redis/issues/120#issue-1667986321)
> Replace BTreeMap by BTreeSet and remove id form Entry

- Cargo.lock
- Cargo.toml
`rand` seems not to be used now.
> Remove unused rand dependency

- Cargo.lock
- Cargo.toml
Updates to `opentelemetry` 0.20.0, and updates `Cargo.lock`.
> Update to opentelemetry 0.20.0

- Cargo.lock
- Cargo.toml
Updates to `tracing-opentelemetry` 0.21.0, and updates Cargo.lock.
> Update to tracing-opentelemetry 0.21.0

- src/db.rs
> fix: expiration bug

- src/bin/server.rs
In latest `opentelemetry-rust` repository, there is no example code for `aws-xray` under the `examples` folder, which still can be found in older commits.
> fix: update aws-xray example link for x-amzn-trace-id

- src/bin/cli.rs
`clap` can use the appropriate `From` trait of the value type.
https://docs.rs/clap/4.5.13/clap/macro.value_parser.html
> Remove unnecessary custom clap value parser
